In [2]:
import numpy as np
import keras
import keras.datasets.mnist
import time

from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import Sequential
from keras.layers import Dense, Flatten


(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
assert x_train.shape == (60000, 28, 28)
assert x_test.shape == (10000, 28, 28)
assert y_train.shape == (60000,)
assert y_test.shape == (10000,) 

print("Sizes...")
print((x_train.shape,y_train.shape))
print((x_test.shape,y_test.shape))

Sizes...
((60000, 28, 28), (60000,))
((10000, 28, 28), (10000,))


In [3]:
# Convert y_train into one-hot format
# !!! Run only once
temp = []
for i in range(len(y_train)):
    temp.append(to_categorical(y_train[i], num_classes=10))
y_train = np.array(temp)
# Convert y_test into one-hot format
temp = []
for i in range(len(y_test)):    
    temp.append(to_categorical(y_test[i], num_classes=10))
y_test = np.array(temp)

In [4]:
print("Sizes...")
print((x_train.shape,y_train.shape))
print((x_test.shape,y_test.shape))

Sizes...
((60000, 28, 28), (60000, 10))
((10000, 28, 28), (10000, 10))


In [64]:
n=1000
model4 = Sequential()
model4.add(Flatten(input_shape=(28,28)))
model4.add(Dense(n, activation='relu'))
model4.add(Dense(n, activation='relu'))
model4.add(Dense(10, activation='softmax'))

model4.compile(loss='categorical_crossentropy', 
              optimizer='adam',
              metrics=['acc'])

In [65]:
start = time.time()
model4.fit(x_train, y_train, epochs=10,validation_data=(x_test,y_test))
end = time.time()

Epoch 1/10
1875/1875 [==============================] - 18s 10ms/step - loss: 1.5101 - acc: 0.9140 - val_loss: 0.2002 - val_acc: 0.9476
Epoch 2/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.2040 - acc: 0.9489 - val_loss: 0.3116 - val_acc: 0.9235
Epoch 3/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.1848 - acc: 0.9533 - val_loss: 0.1990 - val_acc: 0.9499
Epoch 4/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.1602 - acc: 0.9588 - val_loss: 0.1899 - val_acc: 0.9525
Epoch 5/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.1496 - acc: 0.9623 - val_loss: 0.1967 - val_acc: 0.9558
Epoch 6/10
1875/1875 [==============================] - 23s 12ms/step - loss: 0.1264 - acc: 0.9684 - val_loss: 0.1376 - val_acc: 0.9705
Epoch 7/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.1181 - acc: 0.9717 - val_loss: 0.1878 - val_acc: 0.9631
Epoch 8/10
1875/1875 [===========================

In [49]:
#model4.summary()

In [66]:
print("-------------------------------------------------")
print("Benchmark Results for this test")
print()
print("Elapsed Time (min):",(end - start)/60.0)
print(end-start, "seconds")
print("-------------------------------------------------")


-------------------------------------------------
Benchmark Results for this test

Elapsed Time (min): 3.3826238473256427
202.95743083953857 seconds
-------------------------------------------------


## Predictions

In [51]:
#len(x_train)

60000

In [67]:
t = 50000
train_sample = x_train[:t]
test_sample = y_train[:t]

start = time.time()
preds = model4.predict(train_sample)
end = time.time()

print(np.around(preds,1))
print(test_sample)
print('Time to classify ', t, ' images : ', end-start)
print('Average time to classify 1 image : ', round((end-start)/t, 4 ))

#np.array_equal(np.around(preds,1),test_sample)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
Time to classify  50000  images :  2.503750801086426
Average time to classify 1 image :  0.0001


In [10]:
import sys
print(model4)
sys.getsizeof(model4)

48

In [11]:
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('CPU')
print(len(physical_devices))

1
